pipeline:
  loader:
    target: manager.Downloader
    args:
      configs:
        - config/datasets/data-config.yaml
  manager:
    target: manager.ASR2TTSRunner
  processors:
    - name: downloader
      target: modules.Downloader
    - name: voice_activity_detection
      target: modules.VoiceActivityDetection
      args:
        model_choice: webrtc_voice_activity_detection
    - name: denoiser
      target: modules.DenoiseAudio
      args:
        model_choice: master64
        dry: 0
    - name: superres
      target: modules.SuperResAudio
      args:
        model_choice: voicefixer