pipeline:
  loader:
    target: manager.Downloader
    args:
      configs:
        - config/datasets/data-config.yaml
      save_dir: raw_data/yt_data
  manager:
    target: manager.YoutubeRunner
  processors:
    - name: chunking
      target: modules.AudioChunking
      args:
        model_choice: pydub_chunking
    - name: denoise_audio
      target: modules.DenoiseAudio
      args:
        model_choice: meta_denoiser_dns48